### ISSUE TITLE
Questions and Issues of scHiCDiff.norm()

### ISSUE THREAD

**Issue by hamy12398** [wmalab/scHiCDiff#2]
Good morning,

I have a question about bias.info.path in scHiCDiff.norm(). You mentioned 'The generation of these items is available at http://dna.cs.miami.edu/scHiCNorm.' However, I found it difficult to gather the request information from the website. Can you give me detail and some examples about this 'bias.info.path'?

I tried to assumed '22.bin_features_1000000' from the website as bias.info.path in scHiCDiff.norm() and a N*N scHi-C matrix. I got the error 'Using Negative Ninomial Hurdle. 
Error in hurdle(vec_HiC ~ vec_density + vec_GC + offset(vec_map) | vec_density + :
empty model'

I am looking forward to your support. I am appreciated your help.

Thank you,

My Nguyen (Jasmine)

Graduate Ph.D. Student
Department of Biostatistics
Virginia Commonwealth University School of Population Health

**Comment by mdozmorov** [comment]
A more fundamental question, how to generate the bias files for different restriction enzymes and resolutions. The files at http://dna.cs.miami.edu/scHiCNorm/ are specific to DpnII and 1M. I cannot understand how `*.bin_features_1000000` files are created from `*.fends_GC`, `*.fends_mappability`, `*.indexes_mapped_uniquely`. Coordinates in `fends_GC` and `fends_mappability` differ by 1 (apparently, 0- and 1-based). Is there a documentation?

**Comment by lhlruc** [comment]
Thank you for your interest of my research.  If the four reference genomes (i.e., hg19, hg38, mm9 and mm10) are of your interest, you can simply download the source code and corresponding reference genome files from http://dna.cs.miami.edu/scHiCNorm/.  You don't need to go through the steps 1&2 in readme and can directly perform the third step using the code "perl your_path/scHiCNorm_source_code/scripts/generate_bin_features.pl  your_path/scHiCNorm_source_code/data/rg_mouse_mm9.len 50000(resolution)  your_output_path" to generate the bias files with different resolutions. 

Since I only applied the code on data specific to DpnII, I have no idea about generating the bias files for different restriction enzymes. Please try to contact the authors of scHiCNorm to find the answer.

**Comment by hamy12398** [comment]
Thank you for your response. I tried to create feature for other resolution. I followed your suggestion "perl your_path/scHiCNorm_source_code/scripts/generate_bin_features.pl your_path/scHiCNorm_source_code/data/rg_mouse_mm9.len 50000(resolution) your_output_path"  with replacement of my path on my command prompt of MacOX. However, I did not see any output. Can you help me with this?

**Comment by lhlruc** [comment]
> Thank you for your response. I tried to create feature for other resolution. I followed your suggestion "perl your_path/scHiCNorm_source_code/scripts/generate_bin_features.pl your_path/scHiCNorm_source_code/data/rg_mouse_mm9.len 50000(resolution) your_output_path" with replacement of my path on my command prompt of MacOX. However, I did not see any output. Can you help me with this?

Thank you for your inquiry. I'm curious if you've previously downloaded the feature files for a particular reference genome from http://dna.cs.miami.edu/scHiCNorm/data/scHiCNorm_features/ and saved them in your_output_path. In step 3, you'll be using the fends_GC, fends_mappability, and indexes_mapped_uniquely files to create bin_features_resolution files, and the aforementioned three types of files should reside in the same directory as the generated files.

**Comment by hamy12398** [comment]
It works. Thank you.
